<?php

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\ManageTrees;
use Fisharebest\Webtrees\Http\RequestHandlers\MergeFactsPage;
use Fisharebest\Webtrees\I18N;

use HuHwt\WebtreesMods\Http\RequestHandlers\MultTreeViewRH;

$cat_checkI = I18N::translate('Individuals');       /** EW.H - MOD ... übersetzte Kategorie auswerten */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ManageTrees::class, ['tree' => $tree->name()]) => I18N::translate('Manage family trees'), $title]]) ?>

<h1><?= $title ?></h1>
<!-- EW.H - MOD ... trees-duplicates extended -->
<?php foreach ($duplicates as $category => $records) : ?>

    <?php if (!empty($records)) : ?>
        <h2><?= $category ?></h2> <?= I18N::translate('count') ?>: <?= count($records) ?>
        <!-- <?php if ($category === $cat_checkI) : ?>       <? /** EW.H - MOD ... Zusatzaktion bei 'Individuals' */ ?>
            <?php var_dump($records) ?>
        <?php endif ?> -->
        <ul>
            <?php foreach ($records as $duplicates) : ?>
                <li>
                    <?= $duplicates[0]->fullName() ?>
                    <?php $xrefs = []; ?>                           <? /** EW.H - MOD ... Struktur für gesammelte XREF */ ?>
                    <?php foreach ($duplicates as $record) : ?>
                        —
                        <a href="<?= e($record->url()) ?>">
                            <?= $record->xref() ?>
                        </a>
                        <?php $xrefs[] = $record->xref() ?>         <? /** EW.H - MOD ... XREF sammeln */ ?>
                    <?php endforeach ?>
                    <?php if (count($duplicates) === 2) : ?>
                        —
                        <a href="<?= e(route(MergeFactsPage::class, ['tree' => $tree->name(), 'xref1' => $duplicates[0]->xref(), 'xref2' => $duplicates[1]->xref()])) ?>">
                            <?= I18N::translate('Merge') ?>
                        </a>
                    <?php endif ?>
                    <?php if ($category === $cat_checkI) : ?>       <? /** EW.H - MOD ... Zusatzaktion bei 'Individuals' */ ?>
                        <?php $xrefs = implode(",", $xrefs) ?>
                        —
                        <a href="<?= e(route(MultTreeViewRH::class, ['tree' => $tree->name(),
                            'xrefs' => $xrefs])) ?>">
                            <?= I18N::translate('Interactive check') ?>
                        </a>
                    <?php endif ?>
                </li>
            <?php endforeach ?>
        </ul>
    <?php else : ?>
        <h2><?= $category ?></h2>
        <p><?= I18N::translate('No duplicates have been found.') ?></p>
    <?php endif ?>
<?php endforeach ?>
