<?php

/**
 * HuH Extensions for webtrees - Multi-Treeview
 * Extensions for webtrees to check and display duplicate Individuals in the database.
 * Copyright (C) 2020-2022 EW.Heinrich
 */

use Fisharebest\Webtrees\Individual;

/**
 * @var Individual  $individual
 * @var string      $age
 */

?>
    <h2 class="wt-page-title mx-auto mtv-info">
        <?= $individual->fullName() ?>, <?= $individual->lifespan() ?> <?= $age ?>
    </h2>
