<?php

/**
 * HuH Extensions for webtrees - Multi-Treeview
 * Extensions for webtrees to check and display duplicate Individuals in the database.
 * Copyright (C) 2020-2022 EW.Heinrich
 */

 use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;

?>

<div class="d-flex mb-4">
    <h2 class="wt-page-title mx-auto">
        <?= $individual->fullName() ?>, <?= $individual->lifespan() ?> <?= $age ?>
    </h2>
</div>