<?php

/**
 * HuH Extensions for webtrees - Multi-Treeview
 * Extensions for webtrees to check and display duplicate Individuals in the database.
 * Copyright (C) 2020-2022 EW.Heinrich
 * 
 * derived from resources/views/modules/interactive-tree/chart.phtml    (wt2.0)
 */

namespace HuHwt\WebtreesMods\Module;

use HuHwt\WebtreesMods\Module\InteractiveTree\InteractiveTreeModMTV;

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;


/**
 * @var Tree        $tree
 * @var string      $XREFindi
 * @var string      $innerHTML
 * @var string      $name
 * @var string      $module
 * @var bool        $withCCE
 */

    $classCCEadapter = 'noCCEadapter';              // there is no CCE instance active ...      -> display: none
    $urlCCEadapter = '';                            // ... so is no need to define a data-definition
    if ($withCCE) {
        $classCCEadapter = '';
        $urlCCEadapter = 'data-url-Cceadapter="' . e(route(InteractiveTreeModMTV::class, ['module' => $module, 'action' => 'CCEadapter', 'tree' => $tree->name(), 'XREFindi' => $XREFindi])) . '"';
    }
?>

<div id="<?= $name ?>_out" class="tv_out" data-url-details="<?= e(route(InteractiveTreeModMTV::class, ['module' => $module, 'action' => 'Details', 'tree' => $tree->name()])) ?>" data-url-individuals="<?= e(route(InteractiveTreeModMTV::class, ['module' => $module, 'action' => 'Individuals', 'tree' => $tree->name()])) ?>" <?= $urlCCEadapter ?> style="height: 300px">
    <div id="<?= $name ?>_tools">
        <ul>
            <li id="<?= $name ?>bCompact" class="tv_button" title="<?= I18N::translate('Use compact layout') ?>">
            </li>
            <li id="<?= $name ?>bClipping" class="tv_button <?= $classCCEadapter ?>" title="<?= I18N::translate('Add this records to the clippings cart') ?>">
            </li>
            <li class="tv_button" id="<?= $name ?>_loading">
                <i class="icon-loading-small"></i>
            </li>
        </ul>
    </div>
    <div id="<?= $name ?>_in" class="tv_in" dir="ltr">
        <?= $innerHTML ?>
    </div>
</div>
